server:
  port: 8010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/management?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: equipment-provider
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
