spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: 01-securitu
  redis:
    host: 139.129.94.24
    port: 6379
    password: password
    timeout: 1000
#  security:
#    user:
#      name: admin

#      password: admin1
server:
    port: 8080
